import { NotificationType } from '../../../prisma';

const NotificationTypeEnum = {
  CALLUS_AND_ULCER: 'CALLUS_AND_ULCER',
  ULCER: 'ULCER',
  CALLUS: 'CALLUS',
  DELIVERED: 'DELIVERED',
  SHIPPED: 'SHIPPED',
  VERIFIED_CONFIRMATION: 'VERIFIED_CONFIRMATION',
  UNVERIFIED_REQUEST_PAYMENT: 'UNVERIFIED_REQUEST_PAYMENT',
  VERIFIED_REQUEST_PAYMENT: 'VERIFIED_REQUEST_PAYMENT',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  SCANNED: 'SCANNED',
  ORDER_CONFIRMATION: 'ORDER_CONFIRMATION',
  ADJUSTMENT_NOTICE: 'ADJUSTMENT_NOTICE',
  RESCAN_NOTICE: 'RESCAN_NOTICE',
  CAMPAIGN: 'CAMPAIGN',
  REFERRAL_SUBMIT: 'REFERRAL_SUBMIT',
  REFERRAL_REWARD: 'REFERRAL_REWARD',
  REWARD_SHIPPED: 'REWARD_SHIPPED',
  REWARD_DELIVERED: 'REWARD_DELIVERED',
  COMPLIANCE_NOTICE: 'COMPLIANCE_NOTICE',
  COMPLIANCE_REJECTED_NOTICE: 'COMPLIANCE_REJECTED_NOTICE',
  COMPLIANCE_INFORMATION: 'COMPLIANCE_INFORMATION',
  IN_APP_INFO: 'IN_APP_INFO',
  IN_APP_URGENT: 'IN_APP_URGENT'
} as const satisfies Record<NotificationType, NotificationType> & {
  [K in NotificationType]: K;
};

export const NotificationTypeList = Object.values(NotificationTypeEnum);
