export enum SlicerProfile {
  FUNCTIONAL_CLINICAL = 'FUNCTIONAL_CLINICAL',
  CORK = 'CORK',
  DIABETIC_45 = 'DIABETIC_45',
  DIABETIC_35 = 'DIABETIC_35',
  LDPE = 'LDPE',
  UCBL = 'UCBL',
  FUNCTIONAL_HIKE = 'FUNCTIONAL_HIKE',
  SHELL = 'SHELL',
  ORTHOFEET = 'ORTHOFEET'
}
