export enum SlicerProfile {
  FUNCTIONAL_CLINICAL = 'FUNCTIONAL_CLINICAL',
  CORK = 'CORK',
  DIABETIC_45 = 'DIABETIC_45',
  DIABETIC_35 = 'DIABETIC_35',
  LDPE = 'LDPE',
  UCBL = 'UCBL',
  FUNCTIONAL_HIKE = 'FUNCTIONAL_HIKE',
  DIABETIC_HIKE = 'DIABETIC_HIKE',
  CHARCOT_DEFORMIT = 'CHARCOT_DEFORMIT',
  MANUAL_SLICE = 'MANUAL_SLICE'
}
