packages:
  - 'auth'
  - 'eslint-config'
  - 'prettier-config'
  - 'tsconfig'
  - 'sdk'
  - 'sdk-next'
  - 'sdk-next-edge'
  - 'sdk-stripe'
  - 'services'
  - 'types'
  - 'ui'
  - 'utils'
neverBuiltDependencies: []
