export enum QueueStatus {
  DEV_VALIDATION = 'DEV_VALIDATION',
  PROD_VALIDATION = 'PROD_VALIDATION',
  PRINT_QUEUE = 'PRINT_QUEUE',
  IN_MANUFACTURING = 'IN_MANUFACTURING',
  NEEDS_SHIPPING = 'NEEDS_SHIPPING'
}
