export enum HikeErrorCode {
  // General errors
  ERR_UNKNOWN = 'ERR_UNKNOWN',
  ERR_EMAIL_MAX_LIMIT = 'ERR_EMAIL_MAX_LIMIT',

  // Data errors
  ERR_DATA_NOT_FOUND = 'ERR_DATA_NOT_FOUND',
  ERR_DATA_CONFLICT = 'ERR_DATA_CONFLICT',
  ERR_DATA_INVALID = 'ERR_DATA_INVALID',

  // Account errors
  ERR_TOKEN_INVALID = 'ERR_TOKEN_INVALID',
  ERR_2FA_INVALID = 'ERR_2FA_INVALID',
  ERR_ACCOUNT_RECOVERY_TYPE_INVALID = 'ERR_ACCOUNT_RECOVERY_TYPE_INVALID',
  ERR_PATIENT_SIGNUP_NOT_ALLOWED = 'ERR_PATIENT_SIGNUP_NOT_ALLOWED',

  // User errors
  ERR_USER_NOT_ACTIVE = 'ERR_USER_NOT_ACTIVE',
  ERR_USER_TERMS_NOT_ACCEPTED = 'ERR_USER_TERMS_NOT_ACCEPTED',
  ERR_USER_CLINICIAN_NOT_FOUND = 'ERR_USER_CLINICIAN_NOT_FOUND',
  ERR_USER_PATIENT_NOT_FOUND = 'ERR_USER_PATIENT_NOT_FOUND',
  ERR_USER_PATIENT_FORBIDDEN = 'ERR_USER_PATIENT_FORBIDDEN',
  ERR_USER_CLINICIAN_ALREADY_EXISTS = 'ERR_USER_CLINICIAN_ALREADY_EXISTS',

  // Company errors
  ERR_COMPANY_USER_NOT_ASSOCIATED = 'ERR_COMPANY_USER_NOT_ASSOCIATED',
  ERR_COMPANY_INVITATION_INVALID = 'ERR_COMPANY_INVITATION_INVALID',

  // Workbench errors
  ERR_WORKBENCH_ALREADY_PROCESSING = 'ERR_WORKBENCH_ALREADY_PROCESSING',

  // Workflow errors
  ERR_USER_WORKFLOW_FORBIDDEN = 'ERR_USER_WORKFLOW_FORBIDDEN',

  // OIDC/SSO errors
  ERR_OIDC_FACILITY_NOT_FOUND = 'ERR_OIDC_FACILITY_NOT_FOUND',
  ERR_OIDC_PATIENT_CLAIM_MISSING = 'ERR_OIDC_PATIENT_CLAIM_MISSING',
  ERR_OIDC_FACILITY_CLAIM_MISSING = 'ERR_OIDC_FACILITY_CLAIM_MISSING',
  ERR_OIDC_INVALID_GRANT = 'ERR_OIDC_INVALID_GRANT',
  ERR_OIDC_TOKEN_EXCHANGE_FAILED = 'ERR_OIDC_TOKEN_EXCHANGE_FAILED',
  ERR_OIDC_NONCE_VALIDATION_FAILED = 'ERR_OIDC_NONCE_VALIDATION_FAILED',
  ERR_OIDC_STATE_VALIDATION_FAILED = 'ERR_OIDC_STATE_VALIDATION_FAILED'
}
