export const AuditAction = {
  CREATE: 'CREATE',
  RETRIEVE: 'RETRIEVE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  IMPORT: 'IMPORT',
  NOTIFY: 'NOTIFY',
  LOGIN_FAILED: 'LOGIN_FAILED',
  TAG_ADD: 'TAG_ADD',
  TAG_REMOVE: 'TAG_REMOVE',
  LABEL_PRINT: 'LABEL_PRINT',
  LABEL_REPRINT: 'LABEL_REPRINT',
  REVIEW: 'REVIEW',
  SEND_REPRINT_JOB: 'SEND_REPRINT_JOB',
  KT_COMPLETE: 'KT_COMPLETE'
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];
