export enum SlicerProfile {
  FUNCTIONAL_CLINICAL = 'FUNCTIONAL_CLINICAL',
  CORK = 'CORK',
  DIABETIC_45 = 'DIABETIC_45',
  DIABETIC_35 = 'DIABETIC_35',
  DIABETIC_35_ORTHOFEET = 'DIABETIC_35_ORTHOFEET',
  DIABETIC_45_ORTHOFEET = 'DIABETIC_45_ORTHOFEET',
  LDPE = 'LDPE',
  SHELL = 'SHELL',
  FUNCTIONAL_HIKE = 'FUNCTIONAL_HIKE'
}
